name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyzer
      run: flutter analyze

    - name: Run Flutter Format
      run: flutter format --set-exit-if-changed .

    - name: Run Unit Tests
      run: flutter test

    - name: Run Integration Tests
      run: flutter drive --target=integration_test/app_test.dart

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: build-apk
        path: build/app/outputs/flutter-apk/app-release.apk
