name: Flutter CI/CD

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build web app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Windows app
        run: flutter build windows --release

      - name: Archive Windows build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/
